name: test

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev, feat/stakeManager]

env:
    FOUNDRY_PROFILE: ci

jobs:
    check:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Get node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Run Forge build
              run: |
                  forge --version
                  forge build --sizes
              env:
                RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
                RPC_URL: ${{ secrets.RPC_URL }}
              id: build

            - name: Run Forge tests
              # ! revert back to FOUNDRY_PROFILE=intense forge test -vvv
              run: forge test -vvv
              env:
                RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
                RPC_URL: ${{ secrets.RPC_URL }}
              id: test
